spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: root_pan
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
  redis:
    host: 140.143.154.143
    port: 6379
    password: redisroot
logging:
  level:
    com:
      pan:
        sbs:
          security:
            mapper: debug
    org:
      springframework:
        security: info

crm:
  login:
    url: /users/login

######## jwt


jwt:
  header: Authorization
  secret: mySecret
  expiration: 5
  tokenHead: Bearer
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: auth/register